name: wishfly_api_client
description: Flutter API client for Wishfly. Feature requests and voting without leaving your app.
version: 0.4.0
repository: https://github.com/Wishfly-dev/api_client

environment:
  sdk: ^3.0.0

dependencies:
  http: ^0.13.3
  wishfly_shared: ^0.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.4.0
  build_runner: ^2.4.4
